### ISSUE TITLE
[Linux/Mac] 'title_name_stripped' referenced before assignment.

### ISSUE THREAD

**Issue by AliceTheGorgon** [Plailect/PlaiCDN#22]
```
Traceback (most recent call last):
  File "PlaiCDN.py", line 559, in <module>
    title_name_stripped, region, product_code, publisher, crypto_seed, curr_version, title_size = getTitleInfo(title_id)
  File "PlaiCDN.py", line 343, in getTitleInfo
    return(title_name_stripped, region, product_code, publisher, crypto_seed, curr_version, title_size)
UnboundLocalError: local variable 'title_name_stripped' referenced before assignment
```

`title_name_stripped` only gets assigned a value `if 'Windows' in platform.system():`

The solution seems to be placing:
```
    else:
        title_name_stripped = title_name
```
after the:
```
    # some windows unicode character bullshit
    if 'Windows' in platform.system():
        title_name_stripped = ''.join([i if ord(i) < 128 else ' ' for i in title_name])
        publisher = ''.join([i if ord(i) < 128 else ' ' for i in publisher])
```

lines, so that title_name_stripped gets a value on non-Windows OSes.

Note: I have no idea if any other OSes would also have to worry about unicode issues, but it seems to work fine on my Linux box.

**Comment by Plailect** [comment]
Fixed
