### ISSUE TITLE
Makerom can't be found even if in directory

### ISSUE THREAD

**Issue by ev1l0rd** [Plailect/PlaiCDN#6]
When I try to download and decrypt a game, I get this error:

```
Traceback (most recent call last):
  File "PlaiCDN.py", line 359, in <module>
    call(dotcia_command_array, stdout=DEVNULL, stderr=STDOUT)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'makerom'

```

I do have makerom in the same directory as shown here:
![screenshot from 2016-04-09 12 54 39](https://cloud.githubusercontent.com/assets/13433513/14403308/682b17d6-fe52-11e5-805b-89909892b543.png)

The command is run inside the PlaiCDN directory. All files are `chmod +x` to allow execution.

**Comment by Plailect** [comment]
Fixed
